/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;


public class App {

    public static void main(String[] args) throws FileNotFoundException {
        ArrayList<Quote> quotes = readFile("src/main/resources/recentquotes.json");

        int randomQuoteLocation = generateRandomNumberBetween(0, quotes.size());

        System.out.println(quotes.get(randomQuoteLocation));
    }




    // read in the file, return it as an array of quote objects
        // in: file location (String)
        // out: ArrayList<Quote>

    public static ArrayList<Quote> readFile(String fileLocation) throws FileNotFoundException {
        FileReader reader = new FileReader(fileLocation);

        Gson gson = new Gson();

        // https://stackoverflow.com/questions/4318458/how-to-deserialize-a-list-using-gson-or-another-json-library-in-java
        ArrayList<Quote> quotes2 = gson.fromJson(reader, new TypeToken<ArrayList<Quote>>(){}.getType());

        return quotes2;
    }


    // generate a random number between two given values (zero and length of quotes array)
        // in: min & max
        // out: random int between
        // min is inclusive, max is not
    public static int generateRandomNumberBetween(int min, int max){
        // cite source here
        if ( min >= max ){
            throw new IllegalArgumentException("max must be greater than min");
        }
        int ranNum = (int)((Math.random() * max ) + min);
        return ranNum;
    }



}
